AWSTemplateFormatVersion: '2010-09-09'
Description: 'Email Summary System Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment type

Resources:
  EmailSummaryLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: EmailSummaryCustomPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/email-summary/*'

  EmailSummaryFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'email-summary-${Environment}'
      Handler: app.lambda_handler.handler
      Role: !GetAtt EmailSummaryLambdaRole.Arn
      Code:
        S3Bucket: !Ref DeploymentBucket
        S3Key: !Ref DeploymentPackage
      Runtime: python3.9
      Timeout: 300
      MemorySize: 256
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment

  EmailSummaryScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Schedule for Email Summary Lambda Function
      ScheduleExpression: rate(10 minutes)
      State: ENABLED
      Targets:
        - Arn: !GetAtt EmailSummaryFunction.Arn
          Id: EmailSummarySchedule

  EmailSummarySchedulePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref EmailSummaryFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EmailSummaryScheduleRule.Arn

Outputs:
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt EmailSummaryFunction.Arn
