name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .  # インストール時のエラーを防ぐため、開発モードでインストール

    - name: Run isort
      run: |
        isort . --check-only --diff

    - name: Run black
      run: |
        black . --check --diff

    - name: Run mypy
      run: |
        mypy app tests

    - name: Run pylint
      run: |
        pylint app tests

    - name: Run flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

    - name: Security check with bandit
      run: |
        bandit -r . -c pyproject.toml

    - name: Check dependencies for known security vulnerabilities
      run: |
        safety check

    - name: Run tests
      run: |
        pytest --cov=app --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        fail_ci_if_error: true
